config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :vehicles, only: %i[index show new create edit update destroy] do
    resources :reservations, only: %i[new create]
    resources :reviews, only: %i[new create]
  end
  resources :reservations, only: %i[index destroy]
  resources :users do
    collection do
      get :dashboard
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :user_name, presence: true, uniqueness: true
  # validates :password, presence: true, length: { minimum: 6 }
  # validates :email, presence: true, uniqueness: true

  validates :address, presence: true
  has_many :vehicles, dependent: :delete_all
  has_many :reservations, dependent: :destroy
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_many :reservations, dependent: :destroy
  has_many :reviews, dependent: :destroy

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { only_integer: true, greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[user_name address photo])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
    @user = current_user
    @reservation = Reservation.new
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @vehicle.available = false
    @user = current_user
    @reservation.vehicle = @vehicle
    @reservation.user = @user
    @reservation.save
    redirect_to reservations_path
  end

  def index
    @vehicles = Vehicle.where(user_id: current_user)
    @reservations = Reservation.where(user_id: current_user)
  end

  def destroy

  end

  private

  def reservation_params
    params.require(:reservation).permit(:start_date, :end_date)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @vehicle = Vehicle.find(params[:vehicle_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @vehicle = Vehicle.find(params[:vehicle_id])
    @review.vehicle = @vehicle
    @review.user = current_user

    if @review.save
      @vehicle.update(available: true)
      redirect_to reservations_path
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def dashboard
    @vehicles = Vehicle.where(user_id: current_user)
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    @vehicles = Vehicle.all
    @markers = @vehicles.geocoded.map do |vehicle|
      {
        lat: vehicle.latitude,
        lng: vehicle.longitude
      }
    end
  end

  def show
    @vehicle = Vehicle.find(params[:id])
    @reservation = Reservation.new
    @reviews = Review.where(vehicle_id: params[:id])
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user
    @vehicle.available = true

    if @vehicle.save!
      redirect_to vehicles_path
    else
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])

    @vehicle.update(vehicle_params)
    redirect_to dashboard_users_path(@vehicle)
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    redirect_to dashboard_users_path(@vehicle)
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:title, :address, :description, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EMove</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://cdn.wallpaper.com/main/styles/responsive_1460w_scale/s3/py_dark_shot06_reslow.jpg?itok=Di2z-G8A);">
  <div class="container">
    <h1>Welcome to E-move!</h1>
    <p>For people who like to move it, move it</p>
    <div class="btn btn-flat">
      <%= link_to 'SEE ALL VEHICULES', vehicles_path, class: "btn btn-flat" %>
    </div>
  </div>
</div>

<div class="about">
<h2> "Enabling everyone to take part in the world's transition to sustainable energy" </h2>
</div>

app/views/reservations/index.html.erb
<div class="exterior_container">
  <div class="my_title_container">
    <h1>Current reservations</h1>
  </div>
  <div class="subtitles">
    <h2><%= link_to "My Vehicles", dashboard_users_path, class: "non-selected"%></h2>
    <h2><%= link_to "My Reservations", reservations_path, class: "selected"%></h2>
  </div>

  <% @reservations.each do |reservation| %>
    <div class="card-product-dashboard">
      <%= cl_image_tag reservation.vehicle.photo.key, height: 300, width: 400, crop: :fill %>
      <div class="dashboard-card-info">
        <div class="card-product-info">
          <div class="top-section">
            <div class="basic-infos">
              <h2><%= reservation.vehicle.title%></h2>
              <p><%= reservation.vehicle.description%></p>
            </div>
            <div style="vertical-align">
              <% if reservation.vehicle.available %>
                <span class="badge finished">Finished</span>
              <% else %>
                <span class="badge current">⌛ In Progress</span>
              <% end %>
            </div>
          </div>
        </div>
        <div class="bottom-section">
          <div class="reservation-infos">
            <div>
              <% days = ((reservation.end_date) - (reservation.start_date)).to_i  %>
              <h2><%= (days * reservation.vehicle.price) + reservation.vehicle.price%> CHF</h2>
            </div>
          </div>
          <div class="dashboard-buttons">
            <div class="owner-infos">
              <div class="avatar_h5">
                <% user = User.find(reservation.user_id) %>
                <h5>
                  <% if user.photo.attached? %>
                    <%= cl_image_tag user.photo.key, id: "avatar-bordered" %>
                  <% else %>
                    <img src="https://picsum.photos/200/200" id="avatar-bordered" />
                  <% end %>
                </h5>
                <h6><%= reservation.vehicle.user.user_name%></h6>
              </div>
              <p>📅 From: <%=reservation.start_date%> to <%=reservation.end_date%></p>
            </div>
            <div class="buttons">
              <% unless reservation.vehicle.available %>
               <%= link_to("Finish", new_vehicle_review_path(reservation.vehicle), class: "btn btn-outline-secondary") %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/reservations/new.html.erb
<div class="exterior_container">
  <div class="main_container">
    <%= simple_form_for [@vehicle, @reservation] do |f| %>
      <%= f.input :start_date, as: :date, html5: true %>
      <%= f.input :end_date, as: :date, html5: true %>
      <%= f.submit "Book", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="reviews-container">
  <h3>Add Review</h3>
  <div class="review">
    <% reservation = Reservation.where('user_id=? AND vehicle_id=?', current_user, @vehicle).first %>
    <div class="review-card">
      <div class="card-trip">
          <%= cl_image_tag reservation.vehicle.photo.key, height: 300, width: 400, crop: :fill %>
          <div class="card-trip-infos">
            <div>
                <h2><%= reservation.vehicle.title %></h2>
                <p>Start Date: <%=reservation.start_date%></p>
                <p>End Date: <%=reservation.end_date%></p>
            </div>
            <div class="avatar_h5">
              <% user = User.find(reservation.user_id) %>
              <h5>
                 <% if user.photo.attached? %>
                    <%= cl_image_tag user.photo.key, class: "card-trip-user avatar-bordered" %>
                  <% else %>
                    <img src="https://picsum.photos/200/200" class="card-trip-user avatar-bordered" />
                  <% end %>
              </h5>
            </div>
            <% days = ((reservation.end_date) - (reservation.start_date)).to_i  %>
            <h2><%= (days * reservation.vehicle.price) + reservation.vehicle.price%> CHF</h2>
          </div>
      </div>
    </div>
    <div class="review-form-stars">
      <div class="review-stars">
        <i class="fa fa-star" data-rating=1 aria-hidden="true"></i>
        <i class="fa fa-star" data-rating=2 aria-hidden="true"></i>
        <i class="fa fa-star" data-rating=3 aria-hidden="true"></i>
        <i class="fa fa-star" data-rating=4 aria-hidden="true"></i>
        <i class="fa fa-star" data-rating=5 aria-hidden="true"></i>
      </div>
      <%= simple_form_for [@vehicle, @review], html: { id: 'review-form'} do |f| %>
        <%= f.input :comment, as: :text, label: false, placeholder: 'Leave your review' %>
        <%= f.input :rating , as: :hidden, input_html: { value: 0 } %>
        <%= f.submit 'Add' %>
      <% end %>
      <%= link_to('Back', reservations_path, class: 'btn btn-outline-secondary') %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon Lausanne
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to  root_path, class: "navbar-brand" do %>
    <%= image_tag "logo_nav_e-move.svg" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to "All Vehicles", vehicles_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Dashboard", dashboard_users_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path , method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
        <% if current_user.photo.attached? %>
          <%=cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false%>
        <% else %>
          <%= image_tag "https://i2.wp.com/www.cssscript.com/wp-content/uploads/2020/12/Customizable-SVG-Avatar-Generator-In-JavaScript-Avataaars.js.png?fit=438%2C408&ssl=1", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
        </div>
      </li>
      <% else %>
        <li><%= link_to "Login", new_user_session_path, class: "nav-link" %></li>
        <li class="nav-item">
          <%= link_to "Register", new_user_registration_path, class: "btn-get" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/dashboard.html.erb
<div class="exterior_container">
  <div class="my_title_container">
    <h1>My Dashboard</h1>
    <div class="index-button">
      <%= link_to('Add', new_vehicle_path) %>
    </div>
  </div>
  <div class="subtitles">
  <h2><%= link_to "My Vehicles", dashboard_users_path, class: "selected"%></h2>
  <h2><%= link_to "My Reservations", reservations_path, class: "non-selected"%></h2>
  </div>
    <% @vehicles.each do |vehicle| %>
      <div class="card-product-dashboard">
        <%= cl_image_tag vehicle.photo.key, height: 300, width: 400, crop: :fill %>
        <div class="dashboard-card-info">
          <div class="card-product-info">
            <div class="top-section">
              <div class="basic-infos">
                <h2><%= vehicle.title%></h2>
                <p><%= vehicle.description %></p>
              </div>
              <div style="vertical-align">
                <% if vehicle.available %>
                  <span class="badge available">&#X2705; Available</span>
                <% else %>
                  <span class="badge reserved">&#X26D4; In Use</span>
                <% end %>
              </div>
            </div>
          </div>
          <div class="bottom-section">
            <div class="price-info">
              <h2><%= vehicle.price %> CHF</h2>
            </div>
            <div class="dashboard-buttons-dashboard">
              <%= link_to("Edit", edit_vehicle_path(vehicle), class: "btn btn-outline-secondary") %>
              <%= link_to('Delete', vehicle_path(vehicle), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-danger") %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
</div>

app/views/vehicles/edit.html.erb
<div class="exterior_container">
    <div class="reviews-container-sff">
      <h3>Edit your Vehicle</h3>
      <div class="review-sff">
        <div class="review-card-sff">
          <div class="card-trip">
              <%= cl_image_tag @vehicle.photo.key, height: 300, width: 400, crop: :fill %>
              <div class="card-trip-infos">
                <div>
                    <h2><%= @vehicle.title %></h2>
                    <p>Start Date:</p>
                    <p>End Date:</p>
                </div>
                <h2> CHF</h2>
              </div>
          </div>
        </div>
          <%= simple_form_for @vehicle do |f|%>
            <%= f.input :title %>
            <%= f.input :description %>
            <%= f.input :price %>
            <%= f.input :address %>
            <%= f.submit "save your changes" %>
          <% end %>
      </div>
    </div>
</div>

app/views/vehicles/index.html.erb
<div class="container">
   <h2 class="index-title">&#x2B50; Find and rent your dream vehicle &#x2B50;</h2>
    <div class="index-button">
      <%= link_to('Add a vehicle', new_vehicle_path) %>
    </div>
  <div class="row mt-3">
    <div class="col-6">
      <% @vehicles.each do |vehicle| %>
        <div class="card-trip">
          <%= cl_image_tag vehicle.photo.key, height: 300, width: 400, crop: :fill %>
          <div class="card-trip-infos">
            <div>
              <h2><%= link_to(vehicle.title, vehicle_path(vehicle)) %></h2>
              <p>"<%= vehicle.description%>"</p>
            </div>
            <h2 class="card-trip-pricing"><%= vehicle.price %> CHF</h2>
            <% user = User.find(vehicle.user_id) %>
            <% if user.photo.attached? %>
              <%= cl_image_tag user.photo.key, class: "card-trip-user avatar-bordered" %>
            <% else %>
              <img src="https://picsum.photos/200/200" class="card-trip-user avatar-bordered" />
            <% end %>
          </div>
         </div>
        <% end %>
       </div>

       <div class="col-6">
        <div id="map"
          style="width: 100%; height: 600px;"
          data-markers="<%= @markers.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
         </div>
        </div>
       </div>
</div>

app/views/vehicles/new.html.erb
<div class="exterior_container">
  <div class="sign-form">
    <h3>Want to rent your favorite vehicle?</h3>
    <%= simple_form_for @vehicle do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :address %>
        <%= f.input :price %>
        <%= f.input :photo, as: :file %>
        <%= f.submit "Create Vehicle", class: "sign-btn" %>
    <% end %>
    <div class="links">
      <%= link_to('Back', vehicles_path) %>
    </div>
  </div>
</div>

app/views/vehicles/show.html.erb
<div class="container" >
<h1> Reservation </h1>
  <div class="container_cards">
    <div class="card-image">
      <%= cl_image_tag @vehicle.photo.key, width: 400, crop: :fill, class: "img-banner" %>
      <div class="card-product-infos">
        <h2 class= "card_title"><%= @vehicle.title %></h2>
        <p class= "card__dsc"><%= @vehicle.description %></p>
        <p>Rating: <%= @reviews.average(:rating) ? @reviews.average(:rating) : 'Pas de votes' %></p>
      </div>
    </div>

      <!--booking -->

    <div class="booking-widget">
      <div class='booking-widget__header'>
          <figure>
            <figcaption class='header-caption'>
              <h3 id=""><%= @vehicle.title %></h3>
              <span id=""><i class="fa fa-map-marker" aria-hidden="true"></i> <%= @vehicle.address %></span>
              <p><%= @vehicle.price %> CHF</p>
            </figcaption>
          </figure>
      </div>

      <div class='booking-widget__form'>
        <%= simple_form_for [@vehicle, @reservation] do |f| %>
          <label for='check-in'>Check in</label>
          <div id='check-in' class='form-field'>
          <%= f.input :start_date, as: :date, html5: true %>
          </div>

          <label for='check-in'>Check out</label>
          <div id='check-out' class='form-field'>
          <%= f.input :end_date, as: :date, html5: true %>
          </div>

          <%= f.submit "Book", class: "bn3" %>
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <%= link_to('Back', vehicles_path, class: 'bn4') %>
    <% if current_user == @vehicle.user %>
      | <%= link_to('Edit', edit_vehicle_path, class: 'bn4') %>
      | <%= link_to('Delete', vehicle_path(@vehicle), method: :delete, data: { confirm: "Are you sure?" }, class: 'bn4') %>
    <% end %>
  </div>
  <div class="reviews-show-container">
    <h3>Reviews &#x2B50</h3>
    <% @reviews.each do |review| %>
      <div class="review-comment">
        <p class="comment-p"><strong>Comment:</strong> <%= review.comment %></p>
        <p><strong>Author:</strong> <small><%=review.user.user_name %></small> - <small><%= review.created_at %></small></p>
      </div>
    <% end %>
  </div>
</div>